# Generated by Django 5.0.6 on 2024-05-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseOrder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
