# Generated by Django 5.0.6 on 2024-05-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_details', models.CharField(max_length=100)),
                ('vendor_code', models.CharField(max_length=15)),
                ('on_time_delivery_rate', models.FloatField(max_length=15)),
                ('quality_rating_avg', models.FloatField(max_length=15)),
                ('average_response_time', models.FloatField(max_length=15)),
                ('fulfilment_rate', models.FloatField(max_length=15)),
            ],
        ),
    ]
