# Generated by Django 5.0.6 on 2024-05-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='average_response_time',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='fulfilment_rate',
            field=models.IntegerField(max_length=15),
        ),
    ]
